# Generated by Django 5.1.3 on 2025-04-14 08:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quiz_show_results_immediately_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='allow_multiple_attempts',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='points_per_question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='show_correct_answers',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='time_per_question',
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_results_immediately',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
